# Generated by Django 6.0 on 2026-03-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_order_payment_storeproduct_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_video',
            field=models.URLField(blank=True, help_text='URL to recipe video (YouTube, Vimeo, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='User profile photo', null=True, upload_to='profile_photos/'),
        ),
    ]
