# Generated by Django 6.0 on 2026-03-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_favoriterecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='website',
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantlocation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
