# Generated by Django 6.0 on 2026-03-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_restaurantlocation_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
